# Generated by Django 4.2.8 on 2023-12-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('EmployeeFirstName', models.CharField(max_length=50)),
                ('EmployeeLastName', models.CharField(max_length=50)),
                ('EmployeeUsername', models.CharField(max_length=50, unique=True)),
                ('EmployeePassword', models.CharField(max_length=50)),
                ('EmployeeRole', models.CharField(max_length=50)),
                ('EmployeeEmail', models.CharField(max_length=70, unique=True)),
                ('EmployeePhone', models.CharField(max_length=11, unique=True)),
                ('EmployeeType', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('PackageID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('PackageName', models.CharField(max_length=100)),
                ('PackageWeight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('PackageQRCode', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='PackagesCategory',
            fields=[
                ('PackageCategoryID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('PackageCategory', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'PackagesCategory',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('StationID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('StationName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskID', models.IntegerField(primary_key=True, serialize=False)),
                ('SourceLocation', models.CharField(max_length=255)),
                ('DestinationLocation', models.CharField(max_length=255)),
                ('TaskStatus', models.CharField(max_length=10)),
                ('Package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAPP.package')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('StorageLocationID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Alias', models.CharField(max_length=50, unique=True)),
                ('Package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAPP.package')),
            ],
            options={
                'db_table': 'StorageLocations',
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('RobotID', models.IntegerField(primary_key=True, serialize=False)),
                ('RobotStatus', models.CharField(max_length=12)),
                ('BatteryLevel', models.IntegerField()),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WAPP.task')),
            ],
            options={
                'db_table': 'Robot',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='PackageCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WAPP.packagescategory'),
        ),
        migrations.AddField(
            model_name='package',
            name='Station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WAPP.station'),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('LogID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('LogTime', models.DateTimeField()),
                ('LogAction', models.CharField(max_length=1024)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WAPP.employee')),
            ],
            options={
                'db_table': 'Logs',
            },
        ),
    ]
